
FROM maven:3.9.9 AS build



WORKDIR /app


COPY . .


RUN mvn clean package -DskipTests


FROM eclipse-temurin:21-jdk AS build

WORKDIR /app


COPY --from=build /app/target/*.jar app.jar


ENTRYPOINT ["java", "-jar", "app.jar"]
