server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service} #"jdbc:mysql://localhost:3306/identity_service" #identity_service la ten cua database
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root} #root
    password: ${DBMS_PASSWORD:root} #root

    #sau : la gia tri mac dinh neu khong co bien moi truong, o day neu khong co DBMS_CONNECTION se lay jdbc:mysql://.../identity_service
    #neu co bien moi truong no se override len :root dang sau

#    url: "jdbc:mysql://root:syteRIJwoMVoELgzvgJVElpEQGKbtBRX@maglev.proxy.rlwy.net:28113/railway"
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    username: "root"
#    password: "syteRIJwoMVoELgzvgJVElpEQGKbtBRX"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    #local thi xoa
#    database-platform: org.hibernate.dialect.MySQL8Dialect

outbound:
  identity:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  signerKey: "b2yoP+BXkNpTkT3UA7TSAHxqoLxuzgZIRmscynx2zbm5PHbtt3U+JB5N1G6AIrNg"
  valid-duration: 360 #in second
  refreshable-duration: 720